###########
# site.url, site.title
title: One Fat Giraffe
url: "https://onefatgiraffe.com"

# Meta data
# ---------
author:  One Fat Giraffe
keywords:     apps, Vancouver, Canada, web, mobile, media, ios, javascript, php, wordpress, java
language:     en
description: Digital media company based in Vancouver, Canada, focused on interactive media, web and mobile solutions 


# Links
# -----
twitter:      onefatgiraffe
instagram:    onefatgiraffe


########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded



exclude: [
  'Gemfile',
  'Gemfile.lock',
  'Rakefile',
  'README.md',
  'node_modules',
  'vendor',
  'bower.json',
  'package.json',
  'gruntfile.js',
  'CONTRIBUTING.md',
  'LICENSE',
  'components'
  ]

plugins:
  - jekyll-sitemap

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : 'UA-47364644-1'